"""LLM-powered features for WriteDetect.

Adds two Hugging Face LLMs on top of the existing ML/DL detector:
  1. AI Judge      - Qwen2.5-0.5B-Instruct gives an independent human/AI verdict with reasoning.
                      A LoRA fine-tuned version (trained on the WriteDetect dataset, see
                      prepare_finetune_data.py + finetune_ai_judge.py) can be swapped in if its
                      adapter is present under models/qwen_judge_lora/.
  2. Plain Explain - SmolLM2-360M-Instruct turns the classifier's verdict + LIME keywords into a
                      short explanation a non-technical reader can understand.

All models are small enough to run on Hugging Face Spaces' free CPU tier.
"""
import os

import streamlit as st
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

AI_JUDGE_MODEL = "Qwen/Qwen2.5-0.5B-Instruct"
EXPLAIN_MODEL = "HuggingFaceTB/SmolLM2-360M-Instruct"
AI_JUDGE_LORA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "models", "qwen_judge_lora")


def finetuned_judge_available() -> bool:
    """Whether a LoRA-fine-tuned AI Judge adapter has been trained and placed in models/."""
    return os.path.isfile(os.path.join(AI_JUDGE_LORA_DIR, "adapter_config.json"))


@st.cache_resource(show_spinner=False)
def load_ai_judge(use_finetuned: bool = False):
    tokenizer = AutoTokenizer.from_pretrained(AI_JUDGE_MODEL)
    model = AutoModelForCausalLM.from_pretrained(AI_JUDGE_MODEL)

    if use_finetuned and finetuned_judge_available():
        from peft import PeftModel

        model = PeftModel.from_pretrained(model, AI_JUDGE_LORA_DIR)

    return pipeline("text-generation", model=model, tokenizer=tokenizer, max_new_tokens=150)


@st.cache_resource(show_spinner=False)
def load_explainer():
    return pipeline("text-generation", model=EXPLAIN_MODEL, max_new_tokens=120)


def run_ai_judge(text: str, use_finetuned: bool = False) -> dict:
    """Ask the LLM for an independent human-vs-AI verdict and a short justification.

    use_finetuned=True uses the LoRA adapter fine-tuned on the WriteDetect training labels
    (see prepare_finetune_data.py + finetune_ai_judge.py) if one has been trained and placed
    under models/qwen_judge_lora/. Falls back to the base zero-shot model otherwise.
    """
    judge = load_ai_judge(use_finetuned=use_finetuned)
    messages = [
        {
            "role": "system",
            "content": (
                "You are an expert at detecting whether a piece of writing was written by a "
                "human or generated by an AI language model. Be concise and decisive."
            ),
        },
        {
            "role": "user",
            "content": (
                "Read the text below and decide whether it is Human-Written or AI-Generated.\n"
                "Reply in exactly this format:\n"
                "Verdict: <Human-Written or AI-Generated>\n"
                "Reasoning: <one or two short sentences>\n\n"
                f"Text:\n{text[:1500]}"
            ),
        },
    ]

    output = judge(messages, do_sample=False)[0]["generated_text"]
    reply = output[-1]["content"] if isinstance(output, list) else str(output)

    verdict = "Uncertain"
    reasoning = reply.strip()
    for line in reply.splitlines():
        if line.lower().startswith("verdict:"):
            verdict = line.split(":", 1)[1].strip()
        elif line.lower().startswith("reasoning:"):
            reasoning = line.split(":", 1)[1].strip()

    return {"verdict": verdict, "reasoning": reasoning, "raw": reply}


def run_plain_explanation(prediction: str, confidence: float, top_words: list[str] | None = None) -> str:
    """Turn the classifier's prediction + LIME keywords into a plain-English explanation."""
    explainer = load_explainer()
    label = "written by a human" if prediction == "Human Written" else "generated by an AI system"
    words_str = ", ".join(top_words[:10]) if top_words else "its overall writing style and word choice"

    messages = [
        {
            "role": "system",
            "content": (
                "You explain machine learning predictions in simple, plain English for "
                "non-technical readers. Never use jargon. Keep answers to 2-3 sentences."
            ),
        },
        {
            "role": "user",
            "content": (
                f"A text classifier decided a piece of writing was most likely {label}, with "
                f"{confidence:.0%} confidence. It paid the most attention to these words: {words_str}. "
                f"In plain English, explain why a classifier might find those words suspicious or "
                f"telling for deciding the text is {label}."
            ),
        },
    ]

    output = explainer(messages, do_sample=False)[0]["generated_text"]
    reply = output[-1]["content"] if isinstance(output, list) else str(output)
    return reply.strip()
