"""Export the labeled dataset into chat-formatted JSONL for LoRA fine-tuning the AI Judge LLM.

Each example mirrors the exact prompt format used at inference time in llm_utils.run_ai_judge(),
so the fine-tuned model learns to produce the same Verdict/Reasoning structure, grounded in the
real training labels instead of zero-shot guessing.

Run locally (no GPU needed - this only reads the spreadsheet and writes JSONL):
    venv\\Scripts\\python prepare_finetune_data.py

Outputs:
    finetune_data/ai_judge_train.jsonl
    finetune_data/ai_judge_val.jsonl
"""
import json
import os
import random

import pandas as pd

DATA_FILE = r"C:\Users\hamza\Downloads\Class_work\Intro To Ai Agents\AI Human Detection\data\train_data with labels (2).xlsx"
OUT_DIR = "finetune_data"
SAMPLES_PER_CLASS = 1000  # keep the fine-tune fast on free Colab GPU; raise if you have more time
MAX_CHARS = 1500
VAL_FRACTION = 0.1
SEED = 42

SYSTEM_PROMPT = (
    "You are an expert at detecting whether a piece of writing was written by a "
    "human or generated by an AI language model. Be concise and decisive."
)

USER_TEMPLATE = (
    "Read the text below and decide whether it is Human-Written or AI-Generated.\n"
    "Reply in exactly this format:\n"
    "Verdict: <Human-Written or AI-Generated>\n"
    "Reasoning: <one or two short sentences>\n\n"
    "Text:\n{text}"
)

REASONING_BY_LABEL = {
    0: (
        "The phrasing, pacing, and small imperfections in word choice are consistent with how a "
        "human typically writes, rather than the more uniform style common in AI-generated text."
    ),
    1: (
        "The text has the smooth, evenly structured phrasing and somewhat generic word choice that "
        "is commonly seen in AI-generated writing."
    ),
}


def build_example(text: str, label: int) -> dict:
    verdict = "Human-Written" if label == 0 else "AI-Generated"
    assistant_reply = f"Verdict: {verdict}\nReasoning: {REASONING_BY_LABEL[label]}"

    return {
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": USER_TEMPLATE.format(text=text[:MAX_CHARS])},
            {"role": "assistant", "content": assistant_reply},
        ]
    }


def main():
    random.seed(SEED)
    os.makedirs(OUT_DIR, exist_ok=True)

    print(f"Loading {DATA_FILE} ...")
    df = pd.read_excel(DATA_FILE)
    df.columns = ["text", "label"]
    df = df.dropna(subset=["text", "label"])
    df["label"] = df["label"].astype(int)

    parts = []
    for label_value, group in df.groupby("label"):
        parts.append(group.sample(n=min(SAMPLES_PER_CLASS, len(group)), random_state=SEED))
    balanced = pd.concat(parts, ignore_index=True)
    print(f"Selected {len(balanced)} balanced samples ({SAMPLES_PER_CLASS} per class, capped by availability).")

    examples = [build_example(row["text"], row["label"]) for _, row in balanced.iterrows()]
    random.shuffle(examples)

    split_idx = int(len(examples) * (1 - VAL_FRACTION))
    train_examples, val_examples = examples[:split_idx], examples[split_idx:]

    train_path = os.path.join(OUT_DIR, "ai_judge_train.jsonl")
    val_path = os.path.join(OUT_DIR, "ai_judge_val.jsonl")

    with open(train_path, "w", encoding="utf-8") as f:
        for ex in train_examples:
            f.write(json.dumps(ex, ensure_ascii=False) + "\n")

    with open(val_path, "w", encoding="utf-8") as f:
        for ex in val_examples:
            f.write(json.dumps(ex, ensure_ascii=False) + "\n")

    print(f"Wrote {len(train_examples)} training examples to {train_path}")
    print(f"Wrote {len(val_examples)} validation examples to {val_path}")
    print("\nUpload both files to Colab (or copy to TTU HPCC) alongside finetune_ai_judge.py.")


if __name__ == "__main__":
    main()
